version: '3.7'
services:
  backend-service:
    container_name: prod-moneystats-service
    image: ${DOCKER_REPOSITORY}:${APP_VERSION}
    hostname: prod.moneystats.service
    ports:
      - "8005-8006:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=deploy
      - DATABASE_JDBC_URL=${DATABASE_JDBC_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - LOGTAIL_LOGS=${LOGTAIL_LOGS}
      - LOGTAIL_APP_NAME=${LOGTAIL_APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - TOKEN_INVITE=${TOKEN_INVITE}
      - JWT_TIME=${JWT_TIME}
      - CONTEXT_PATH=${CONTEXT_PATH}
      - FE_URL=${FE_URL}
      - SCHEDULER_MARKET_DATA_ACTIVE=true
      - SCHEDULER_FOREX_ACTIVE=true
      #- SCHEDULER_MARKET_DATA_QUANTITY=${SCHEDULER_MARKET_DATA_QUANTITY}
      #- SCHEDULER_MARKET_DATA_DELAY_START=${SCHEDULER_MARKET_DATA_DELAY_START}
      #- SCHEDULER_MARKET_DATA_DELAY_END=${SCHEDULER_MARKET_DATA_DELAY_END}
      - REST_CLIENT_EXCHANGE_RATES_API_TOKEN=${REST_CLIENT_EXCHANGE_RATES_API_TOKEN}
      - REST_CLIENT_ANY_API_TOKEN=${REST_CLIENT_ANY_API_TOKEN}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SHOW_UTILS_EXCEPTION_STACKTRACE=${SHOW_UTILS_EXCEPTION_STACKTRACE}
    deploy:
      replicas: 1
    networks:
      docker-network:
        aliases:
          - prod.moneystats.service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-service.rule=Host(`stg.moneystats.service`)"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8080"

networks:
  docker-network:
    external: true