version: '3.1'
services:
  backend-service:
    container_name: prod-moneystats-service
    image: ${DOCKER_REPOSITORY}:latest
    hostname: prod.moneystats.service
    ports:
      - "8005:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - LOGTAIL_LOGS=${LOGTAIL_LOGS}
      - LOGTAIL_APP_NAME=${LOGTAIL_APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - TOKEN_INVITE=${TOKEN_INVITE}
      - JWT_TIME=${JWT_TIME}
      - CONTEXT_PATH=${CONTEXT_PATH}
      - FE_URL=${FE_URL}
      - SCHEDULER_MARKET_DATA_QUANTITY=${SCHEDULER_MARKET_DATA_QUANTITY}
      - SCHEDULER_MARKET_DATA_DELAY_START=${SCHEDULER_MARKET_DATA_DELAY_START}
      - SCHEDULER_MARKET_DATA_DELAY_END=${SCHEDULER_MARKET_DATA_DELAY_END}
      - REST_CLIENT_EXCHANGE_RATES_API_TOKEN=${REST_CLIENT_EXCHANGE_RATES_API_TOKEN}
    networks:
      docker-network:
        aliases:
          - prod.moneystats.service

networks:
  docker-network:
    external: true