version: '3.1'
services:
  backend-service:
    image: ${DOCKER_REPOSITORY}:latest
    ports:
      - "8000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - LOGTAIL_LOGS=${LOGTAIL_LOGS}
      - LOGTAIL_APP_NAME=${LOGTAIL_APP_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
      - TOKEN_INVITE=${TOKEN_INVITE}
      - JWT_TIME=${JWT_TIME}
      - CONTEXT_PATH=${CONTEXT_PATH}
      - FE_URL=${FE_URL}
    networks:
      - docker-network