server:
  servlet:
    context-path: /moneystats-service
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

rest:
  client:
    github:
      issuesUrl: https://api.github.com/repos/MoneyStats/App/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: https://prod-email-sender.up.railway.app
      sendEmailUrl: /v1/send-email
jwt:
  secret: B71E3A5B2B0834ECC17FAAC9977FE2980C4604E9AAA593C144A94BE9FB4B1EFF
  time: 360000
app:
  invitationCode: ${TOKEN_INVITE}
  fe:
    url: http://localhost:4200