env: Local # Used for Google Cloud LOG
server:
  servlet:
    context-path:
    #context-path: /moneystats-service
spring:
  application:
    name: MoneyStats Service H2
    starter-log: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  codec:
    max-in-memory-size: 2MB
  webflux:
    multipart:
      max-request-size: 2MB
  data:
    redis:
      repositories:
        enabled: false
      enabled: true
      cron: 0 0 1 * * MON
      host: pc-giovanni
      json: false
      password: Innavoig.94
      port: 6379
      sslEnabled: false
      #sslTruststore: path of the truststore (.jks file)
      #sslTruststorePassword: password of the trustore
      username: giovannilamarmora

rest:
  scheduled:
    marketData:
      active: false
      quantity: 250
      delay:
        start: 5000
        #end: 60000
        end: 3600000
    forex:
      active: false
      delay:
        start: 5000
        end: 10800000
  client:
    github:
      baseUrl: https://api.github.com
      issuesUrl: /repos/MoneyStats/moneystats.github.io/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: https://email-sender.giovannilamarmora.com
      sendEmailUrl: /v1/send-email
    coinGecko:
      url: https://api.coingecko.com
      marketDataUrl: /api/v3/coins/markets
    anyApi:
      baseUrl: https://anyapi.io/api
      rates: /v1/exchange/rates
      apiKey: ${REST_CLIENT_ANY_API_TOKEN}
    access-sphere:
      client-id: MONEYSTATS-TEST-01
      token: b967aba2-ae13-4367-af3d-31595aab2229
      baseUrl: http://localhost:8081
      userInfo: /v1/userInfo
      register: /v1/users/register

logging:
  config: classpath:logback-spring.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    io.github.giovannilamarmora: DEBUG
    com.giova.service.moneystats: DEBUG
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,**/api-docs/**,/api-docs,*/,**/dist/**,**/documentation/**"

app:
  version: @project.version@
  shouldNotFilter: "/v1/auth/sign-up,/v1/settings/report/bug,/v1/settings/contact,**/swagger-ui/**,**/api-docs/**,/api-docs,*/,**/dist/**,**/documentation/**"
  invitationCode: ${TOKEN_INVITE}