spring:
  application:
    name: MoneyStats Service Local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moneystats
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  codec:
    max-in-memory-size: 1MB
  webflux:
    multipart:
      max-request-size: 1MB

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,*/js/*,*/images/*,*/favicon.ico,/index.html"

app:
  exception:
    stacktrace: true
  shouldNotFilter: "/v1/auth/sign-up,/v1/auth/login,*/token/refresh,/v1/auth/forgot-password,/v1/auth/reset-password,/v1/app/report/bug,/v1/app/contact,**/swagger-ui/**,/swagger-ui.html,/api-docs,**/api-docs/**,/,/index.html,/documentation/**,/dist/**,/site.webmanifest"