server:
  servlet:
    context-path: ${CONTEXT_PATH}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

rest:
  scheduled:
    marketData:
      delay:
        start: 60000
        end: 3600000
  client:
    github:
      issuesUrl: https://api.github.com/repos/MoneyStats/App/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: http://email.sender:8080/email-sender
      sendEmailUrl: /v1/send-email
    coinGecko:
      url: https://api.coingecko.com
      marketDataUrl: /api/v3/coins/markets

jwt:
  secret: ${JWT_SECRET}
  time: ${JWT_TIME}
app:
  invitationCode: ${TOKEN_INVITE}
  fe:
    url: ${FE_URL}