server:
  servlet:
    context-path: /moneystats-service
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

rest:
  scheduled:
    marketData:
      active: true
      delay:
        start: 5000
        #end: 60000
        end: 3600000
    caching:
      active: true
      cron: 0 0 1 * * MON
  client:
    github:
      baseUrl: https://api.github.com
      issuesUrl: /repos/MoneyStats/App/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: https://oraclewebserver.ddns.net/email-sender
      sendEmailUrl: /v1/send-email
    coinGecko:
      url: https://api.coingecko.com
      marketDataUrl: /api/v3/coins/markets
jwt:
  secret: B71E3A5B2B0834ECC17FAAC9977FE2980C4604E9AAA593C144A94BE9FB4B1EFF
  time: 360000
app:
  logTail:
    active: false
  invitationCode: ${TOKEN_INVITE}
  fe:
    url: http://localhost:4200