server:
  servlet:
    #context-path: /moneystats-service
    context-path:
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moneystats
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

rest:
  scheduled:
    marketData:
      active: false
      quantity: 250
      delay:
        start: 5000
        end: 3600000
    forex:
      active: false
      delay:
        start: 5000
        end: 3600000
    caching:
      active: true
      cron: 0 0 1 * * MON
  client:
    github:
      baseUrl: https://api.github.com
      issuesUrl: /repos/MoneyStats/App/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: https://oraclewebserver.ddns.net/email-sender
      sendEmailUrl: /v1/send-email
    coinGecko:
      url: https://api.coingecko.com
      marketDataUrl: /api/v3/coins/markets
    exchangeRates:
      baseUrl: http://api.exchangerate.host
      rates: /live
      apiKey: ${REST_CLIENT_EXCHANGE_RATES_API_TOKEN}

jwt:
  secret: B71E3A5B2B0834ECC17FAAC9977FE2980C4604E9AAA593C144A94BE9FB4B1EFF
  time: 360000
app:
  logTail:
    active: false
  invitationCode: ${TOKEN_INVITE}
  fe:
    url: http://localhost:4200