spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

rest:
  client:
    github:
      issuesUrl: https://api.github.com/repos/MoneyStats/MoneyStats-Service-Application/issues
      authToken: ${GITHUB_AUTH_TOKEN}

jwt:
  secret: ${JWT_SECRET}
  time: 3600000