env: Local # Used for Google Cloud LOG
server:
  servlet:
    context-path:
    #context-path: /moneystats-service
spring:
  application:
    name: MoneyStats Service H2
    starter-log: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  codec:
    max-in-memory-size: 2MB
  webflux:
    multipart:
      max-request-size: 2MB
  data:
    redis:
      repositories:
        enabled: false
      enabled: false
      cron: 0 0 1 * * *
      host: pc-giovanni
      json: false
      password: password
      port: 6379
      sslEnabled: false
      #sslTruststore: path of the truststore (.jks file)
      #sslTruststorePassword: password of the trustore
      username: username

rest:
  scheduled:
    marketData:
      active: false
      quantity: 250
      delay:
        start: 5000
        #end: 60000
        end: 3600000
    forex:
      active: false
      delay:
        start: 5000
        end: 3600000
    caching:
      active: false
      cron: 0 0 1 * * MON
  client:
    github:
      baseUrl: https://api.github.com
      issuesUrl: /repos/MoneyStats/App/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: https://email-sender.giovannilamarmora.com/
      sendEmailUrl: /v1/send-email
    coinGecko:
      url: https://api.coingecko.com
      marketDataUrl: /api/v3/coins/markets
    exchangeRates:
      baseUrl: http://api.exchangerate.host
      rates: /live
      apiKey: ${REST_CLIENT_EXCHANGE_RATES_API_TOKEN}
    anyApi:
      baseUrl: https://anyapi.io/api
      rates: /v1/exchange/rates
      apiKey: ${REST_CLIENT_ANY_API_TOKEN}

logging:
  config: classpath:logback-spring.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    io.github.giovannilamarmora: DEBUG
    com.giova.service.moneystats: INFO
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/img/*,*/favicon.ico,/login,*/login/*"

jwt:
  secret: B71E3A5B2B0834ECC17FAAC9977FE2980C4604E9AAA593C144A94BE9FB4B1EFF
  time: 360000
app:
  version: @project.version@
  shouldNotFilter: "/v1/auth/sign-up,/v1/auth/login,/v1/auth/forgot-password,/v1/auth/reset-password,/v1/app/report/bug,/v1/app/contact,/swagger-ui/index.html,/swagger-ui/swagger-initializer.js,/v3/api-docs,/v3/api-docs/swagger-config"
  invitationCode: ${TOKEN_INVITE}
  cors: # Disabled
    enabled: false
  fe:
    url: http://localhost:4200