env: ${APP_ENV:Deploy} # Used for Google Cloud LOG
server:
  servlet:
    context-path: ${CONTEXT_PATH}
spring:
  application:
    name: MoneyStats Service
    starter-log: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_JDBC_URL}/${DATABASE_NAME}
    #url: jdbc:mysql://mysqldb:3306/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  data:
    redis:
      enabled: ${REDIS_CACHE_ENABLE}
      cron: 0 0 1 * * *
      host: ${REDIS_CACHE_HOST}
      json: true
      password: ${REDIS_CACHE_PASSWORD}
      port: ${REDIS_CACHE_PORT}
      sslEnabled: false
      #sslTruststore: path of the truststore (.jks file)
      #sslTruststorePassword: password of the trustore
      username: ${REDIS_CACHE_USERNAME}

rest:
  scheduled:
    marketData:
      active: ${SCHEDULER_MARKET_DATA_ACTIVE}
      #quantity: ${SCHEDULER_MARKET_DATA_QUANTITY}
      quantity: 250
      delay:
        #start: ${SCHEDULER_MARKET_DATA_DELAY_START}
        #end: ${SCHEDULER_MARKET_DATA_DELAY_END}
        start: 60000
        end: 3600000
    forex:
      active: ${SCHEDULER_FOREX_ACTIVE}
      delay:
        start: 1800000
        end: 10800000
    caching:
      active: true
      cron: 0 0 1 * * MON
  client:
    github:
      baseUrl: https://api.github.com
      issuesUrl: /repos/MoneyStats/moneystats.github.io/issues
      authToken: ${GITHUB_AUTH_TOKEN}
    emailSender:
      url: http://email.sender:8080
      sendEmailUrl: /v1/send-email
    coinGecko:
      url: https://api.coingecko.com
      marketDataUrl: /api/v3/coins/markets
    exchangeRates:
      baseUrl: http://api.exchangerate.host
      rates: /live
      apiKey: ${REST_CLIENT_EXCHANGE_RATES_API_TOKEN}
    anyApi:
      baseUrl: https://anyapi.io/api
      rates: /v1/exchange/rates
      apiKey: ${REST_CLIENT_ANY_API_TOKEN}

logging:
  config: classpath:logback-google.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    com.giova.service.moneystats: ${LOGGING_LEVEL}
    io.github.giovannilamarmora.utils: ${LOGGING_LEVEL}
    web: INFO
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,*/js/*,*/images/*,*/favicon.ico,/index.html"

jwt:
  secret: ${JWT_SECRET}
  time: ${JWT_TIME}
app:
  version: @project.version@
  exception:
    stacktrace: ${SHOW_UTILS_EXCEPTION_STACKTRACE}
  shouldNotFilter: "/v1/auth/sign-up,/v1/auth/login,/v1/auth/token/refresh,/v1/auth/forgot-password,/v1/auth/reset-password,/v1/app/report/bug,/v1/app/contact,/v1/upload/attachment,**/swagger-ui/**,/v3/api-docs,/v3/api-docs/**,/,/index.html,/documentation/**,/dist/**,/site.webmanifest"
  cors:
    enabled: false # Usando CrossOrigin non ne ho bisogno
  invitationCode: ${TOKEN_INVITE}
  fe:
    url: ${FE_URL}